// Reselve, Reject 그리고 에러 핸들링

const delayAdd = (index, cb, errorCb) => {
  setTimeout(() => {
    if (index > 10) {
      errorCb(`${index}는 10보다 클 수 없습니다.`);
      return;
    }
    console.log(index);
    cb(index + 1);
  }, 1000);
};

delayAdd(
  10,
  (res) => console.log(res),
  (err) => console.error(err)
);

//promise, then&catch 이용, async&await 이용
const delayAdd = (index) =>
  new Promise((resolve, reject) => {
    setTimeout(() => {
      if (index > 10) {
        reject(`${index}는 10보다 클 수 없습니다.`);
        return;
      }
      console.log(index);
      resolve(index + 1);
    }, 1000);
  });

delayAdd(2)
  .then((res) => console.log(res))
  .catch((err) => console.error(err))
  .finally(() => console.log("Done!"));

const wrap = async () => {
  try {
    const res = await delayAdd(12);
    console.log(res);
  } catch (err) {
    console.error(err);
  } finally {
    console.log("Done!");
  }
};
wrap();

// 영화 데이터 받아오는 코드를 이용한 예시
const getMovies = (movieName) => {
  return new Promise((resolve, reject) => {
    fetch(`https://www.omdbapi.com/?apikey=7035c60c&s=${movieName}`)
      .then((res) => res.json())
      .then((json) => {
        console.log("JSON :", json);
        if (json.Response === "False") {
          reject(json.Error);
        }
        resolve(json);
      });
  });
};

getMovies("avatar")
  .then((movies) => {
    console.log("데이터 잘 받아옴!");
    console.log("영화목록 :", movies);
  })
  .catch((error) => {
    console.log("데이터 받아오기 실패!");
    console.log("에러 종류 :", error);
  })
  .finally(() => {
    console.log("오류가 있든 없든 완전 종료됨.");
  });

const wrap = async () => {
  try {
    const movies = await getMovies("avatar");
    console.log("데이터 잘 받아옴!");
    console.log("영화목록 :", movies);
  } catch (error) {
    console.log("데이터 받아오기 실패!");
    console.log("에러 종류 :", error);
  } finally {
    console.log("오류가 있든 없든 완전 종료됨.");
  }
};
wrap();
